DMS/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DMS.Models;

namespace DMS.Controllers
{
    public class AuthenticationController : Controller
    {
        private DiagnosticMS_DBContext db = new DiagnosticMS_DBContext();
        //
        // GET: /Authentication/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignIn(user_info login)
        {
            var admin = db.user_info.Where(m => m.user_id == login.user_id && m.password == login.password && m.user_type == "Administrator").FirstOrDefault();
            var operators = db.user_info.Where(m => m.user_id == login.user_id && m.password == login.password && m.user_type == "operator").FirstOrDefault();
            if (operators != null)
            {
                Session["ComCode"] = operators.com_code.ToString();
                Session["UserId"] = operators.user_id.ToString();
                Session["OpFullName"] = operators.full_name.ToString();
                ViewBag.UserName = operators.full_name.ToString();
                return RedirectToAction("Invoice", "Diagnostic");
            }
            if (admin != null)
            {
                Session["ComCode"] = admin.com_code.ToString();
                Session["UserId"] = admin.user_id.ToString();
                Session["AdFullName"] = admin.full_name.ToString();
                Session["EntryDate"] = admin.entry_date.ToString();
                ViewBag.UserName = admin.full_name.ToString();
                return RedirectToAction("Module", "Authentication");
            }
            else
            {
                ViewBag.Message = string.Format("UserName and Password is incorrect");
                return View();
            }



        }
        public ActionResult Module()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GetCompanyList()
        {
           var GetList=db.com_info.ToList<com_info>();
           return View(GetList);
        }

        public ActionResult CompanyInfo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CompanyInfo(com_info comInfo)
        {
            if (ModelState.IsValid)
            {
                db.com_info.Add(comInfo);
                db.SaveChanges();
                ViewBag.Message = string.Format("Saved Succesfully.");
            }
            else 
            {
                ViewBag.Message = string.Format("Data Is not Saved");
            }
            return View();

        }
     
    }
}

DMS/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DMS.Models;

namespace DMS.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /Dashboard/
        public ActionResult Index()
        {
            if ((string)Session["ComCode"] != null && (string)Session["UserId"] != null)
            {
                //ViewBag.Message = string.Format("Ok");

            }
            else {
                return RedirectToAction("SignIn","Authentication");
            }
            return View();
        }

	}
}

DMS/Views/Authentication/CompanyInfo.cshtml
@model DMS.Models.com_info

@{
    ViewBag.Title = "CompanyInfo";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}


<div class="row">
    <div class="col-lg-6">
        <p>Company Information &nbsp;&nbsp;&nbsp;&nbsp;<b>@ViewBag.Message</b></p>
    </div>
    <div class="col-lg-6">
        <p style="float:right">@Html.ActionLink("Back to List", "GetCompanyList")</p>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="box box-success">
        <div class="box-header with-border">
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-horizontal">

                        @Html.ValidationSummary(true)

                        <div class="form-group">
                            @Html.LabelFor(model => model.com_code, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.com_code)
                                @Html.ValidationMessageFor(model => model.com_code)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.com_name, new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.com_name, new { @class="form-control", placeholder="Company Name"})
                                @Html.ValidationMessageFor(model => model.com_name)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.street_add, new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.street_add, new { @class = "form-control", placeholder = "Company Address" })
                                @Html.ValidationMessageFor(model => model.street_add)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.email, new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.email, new { @class = "form-control", placeholder = "Company Email" })
                                @Html.ValidationMessageFor(model => model.email)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.phone, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.phone)
                                @Html.ValidationMessageFor(model => model.phone)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.mobile, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.mobile)
                                @Html.ValidationMessageFor(model => model.mobile)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.currency_sym, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.currency_sym)
                                @Html.ValidationMessageFor(model => model.currency_sym)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.slogan_text, new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.slogan_text, new { @class = "form-control", placeholder = "Company Description" })
                                @Html.ValidationMessageFor(model => model.slogan_text)
                            </div>
                        </div>

                        @*<div class="form-group">
                            @Html.LabelFor(model => model.date_format, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.date_format)
                                @Html.ValidationMessageFor(model => model.date_format)
                            </div>
                        </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.logo, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.logo)
                                @Html.ValidationMessageFor(model => model.logo)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Submit" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


}

DMS/Views/Authentication/GetCompanyList.cshtml
@model IEnumerable<DMS.Models.com_info>
@{
    ViewBag.Title = "GetCompanyList";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<div class="row">
    <div class="col-lg-6">
        <p>Company Information </p>
    </div>
    <div class="col-lg-6">
        <p style="float:right">@Html.ActionLink("Add New", "CompanyInfo")</p>
    </div>
</div>

<div class="box box-success">
    <div class="box-header">
        <h3 class="box-title">Data Table With Full Features</h3>
    </div>
    <div class="box-body">
        <table class="table table-bordered table-striped" id="example2">
            <thead>
                <tr>
                    <th>Company Code</th>
                    <th>Company Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Mobile</th>
                    <th>Address</th>
                    <th>Action</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.com_code)</td>
                    <td>@Html.DisplayFor(modelItem => item.com_name)</td>
                    <td>@Html.DisplayFor(modelItem => item.email)</td>
                    <td>@Html.DisplayFor(modelItem => item.phone)</td>
                    <td>@Html.DisplayFor(modelItem => item.mobile)</td>
                    <td>@Html.DisplayFor(modelItem => item.street_add)</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit")|
                        @Html.ActionLink("Details", "Edit")|
                        @Html.ActionLink("Delete", "Edit")
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

DMS/Views/Authentication/Module.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Module</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="..//assets/plugins/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="..//assets/plugins/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="..//assets/plugins/Ionicons/css/ionicons.min.css">
   
    <!-- Theme style -->
    <link rel="stylesheet" href="..//assets/css/AdminLTE.min.css">
    <link rel="stylesheet" href="..//assets/css/skins/_all-skins.min.css">
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-green layout-top-nav">
    <div class="wrapper">
        <header class="main-header fixed">
            <nav class="navbar navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                       
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse pull-right" id="navbar-collapse">
                        <ul class="nav navbar-nav">                           
                            <li><a href="#">Log Out</a></li>
                        </ul>
                       
                    </div>
                </div>
                <!-- /.container-fluid -->
            </nav>
        </header>
        <!-- Full Width Column -->
        <div class="content-wrapper fixed">
            <div class="container">
                <!-- Main content -->
                <section class="content">
                    <div class="box box-success">
                        <div class="box-header with-border">
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-lg-3 col-xs-6">
                                        <!-- small box -->
                                        <div class="small-box bg-aqua">
                                            <div class="inner">
                                                <h3>@Html.ActionLink("Diagnostik","Index","Dashboard")</h3>
                                                <p>Module</p>
                                            </div>
                                            <div class="icon">
                                                <i class="ion ion-bag"></i>
                                            </div>
                                            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                                        </div>
                                    </div>
                                    <!-- ./col -->
                                    <div class="col-lg-3 col-xs-6">
                                        <!-- small box -->
                                        <div class="small-box bg-green">
                                            <div class="inner">
                                                <h3>HRM</h3>
                                                <p>Module</p>
                                            </div>
                                            <div class="icon">
                                                <i class="ion ion-stats-bars"></i>
                                            </div>
                                            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                                        </div>
                                    </div>
                                    <!-- ./col -->
                                    <div class="col-lg-3 col-xs-6">
                                        <!-- small box -->
                                        <div class="small-box bg-yellow">
                                            <div class="inner">
                                                <h3>Accounts</h3>
                                                <p>Module</p>
                                            </div>
                                            <div class="icon">
                                                <i class="ion ion-person-add"></i>
                                            </div>
                                            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                                        </div>
                                    </div>
                                    <!-- ./col -->
                                    <div class="col-lg-3 col-xs-6">
                                        <!-- small box -->
                                        <div class="small-box bg-red">
                                            <div class="inner">
                                                <h3>Others</h3>
                                                <p>Unique Visitors</p>
                                            </div>
                                            <div class="icon">
                                                <i class="ion ion-pie-graph"></i>
                                            </div>
                                            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                                        </div>
                                    </div>
                                    <!-- ./col -->
                                </div>
                                <!-- /.row -->
                            </div>
                        </div>
                    </div>
                </section>
                <!-- /.content -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="container">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 2.4.0
                </div>
                <strong>Copyright &copy; @DateTime.Now.Year - My ASP.NET Application</strong>
                All rights reserved For <a href="http://www.updatetechno.net">www.updatetechno.com</a>
            </div>
            <!-- /.container -->
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="..//assets/plugins/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="..//assets/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="..//assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="..//assets/plugins/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="..//assets/js/adminlte.min.js"></script>
    <!-- Extra Js -->
    <script src="..//assets/js/main.js"></script>
</body>
</html>

DMS/Views/Authentication/SignIn.cshtml
@model DMS.Models.user_info
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>DMS || SignIn</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="../../assets/plugins/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../assets/plugins/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="../../assets/plugins/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../assets/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="../../plugins/iCheck/square/blue.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <style>
        html, body {
            width: 100%;
            height: 100%;
        }

        .login-bg {
            background-size: cover;
            background-position: center;
            position: relative;
            z-index: 1;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
        }

            .login-bg::before {
                position: absolute;
                z-index: -1;
                left: 0;
                top: 0;
                width: 100%;
                height: 100%;
                content: "";
                background: #000;
                opacity: .6;
            }
        .login-box, .register-box {
            margin: 0 auto;
        }

        .login-logo a, .register-logo a {
            color: #fff;
        }

        .icheck > label {
            padding-left: 20px;
        }

    </style>
</head>
<body class="hold-transition login-page login-bg" style="background-image: url(../assets/img/medical.jpg);">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="login-box">
            <div class="login-logo">
                <a href="#"><b>Admin</b>DMS</a>
            </div>
            <!-- /.login-logo -->
            <div class="login-box-body">
                <p class="login-box-msg">Sign in to start your session</p>

                <div class="form-group has-feedback">
                    @Html.TextBoxFor(model => model.user_id, new { @class = "form-control", placeholder = "Email" })
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    @Html.TextBoxFor(model => model.password, new { @class = "form-control", placeholder = "Email", type = "password" })
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox"> Remember Me
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <input type="submit" class="btn btn-primary btn-block btn-flat" value="Sign In">
                    </div>
                    <label>@ViewBag.Message</label>
                    <!-- /.col -->
                </div>
                @*<div class="social-auth-links text-center">
                        <p>- OR -</p>
                        <a href="#" class="btn btn-block btn-social btn-facebook btn-flat">
                            <i class="fa fa-facebook"></i> Sign in using
                            Facebook
                        </a>
                        <a href="#" class="btn btn-block btn-social btn-google btn-flat">
                            <i class="fa fa-google-plus"></i> Sign in using
                            Google+
                        </a>
                    </div>*@
                <!-- /.social-auth-links -->

                <a href="#">I forgot my password</a><br>
            </div>
            <!-- /.login-box-body -->
        </div>
    }

    <!-- /.login-box -->
    <!-- jQuery 3 -->
    <script src="../../assets/plugins/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="../../assets/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="../../plugins/iCheck/icheck.min.js"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' /* optional */
            });
        });
    </script>
</body>
</html>