DMS/Controllers/DiagnosticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using DMS.Models;
using System.Text;
namespace DMS.Controllers
{
    public class DiagnosticController : Controller
    {
        //
        // GET: /Diagnostic/
        private DiagnosticMS_DBContext db = new DiagnosticMS_DBContext();

        public ActionResult Index()
        {

            return View();
        }
        //[HttpPost]
        //    public ActionResult Index(CodeModel model)
        //    {
        //        var selectCodes = model.codes.Where(x => x.IsCheked == true).ToList<code>();
        //        return Content(string.Join("-", selectCodes.Select(x => x.code1)));
        //    }

        [HttpGet]
        public ActionResult Invoice()
        {
            customer_info cusInfo = new customer_info();

            cusInfo.doctors = db.doctors_info.ToList<doctors_info>();
            cusInfo.codes = db.codes.ToList<code>();


            return View(cusInfo);
        }

        [HttpPost]
        public ActionResult Invoice(customer_info customers)
        {
            if ((string)Session["ComCode"] != null && (string)Session["UserId"] != null)
            {

               // StringBuilder sb = new StringBuilder();
                //code cod = new code();

                foreach (var item in customers.codes)
                {
                   if (item.IsCheked)
                   {
                        //sb.Append(item.code1 + ",");

                        //var quan = db.codes.Where(x => x.code1 == item.code1).FirstOrDefault();
                        //if (quan != null)
                        //{
                        //    ViewBag.testname = quan.code1;
                        //    ViewBag.price = quan.test_price;
                            

                      //  }
                      // ViewBag.testname=item.code1.ToString();
                      //ViewBag.price=item.test_price.ToString();
                        customers.com_code = (string)Session["ComCode"];
                        customers.added_by = (string)Session["UserId"];
                        //db.customer_info.Add(customers);
                        //db.SaveChanges();
                        //ViewBag.Message = string.Format("Saved Successfully");
                        //return RedirectToAction("CustomInvoice");
                    }

                   // ViewBag.Message = sb.ToString();
                }

            }
            return View(customers);
        }

        public ActionResult CustomInvoice()
        {
            return View();
        }



        //add Doctor Information
        public ActionResult doctorInfo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult doctorInfo(doctors_info docInfo)
        {
            if (ModelState.IsValid)
            {
                db.doctors_info.Add(docInfo);
                db.SaveChanges();
                ViewBag.Message = string.Format("Saved Successfully");
            }
            return View(docInfo);
        }
        [HttpGet]
        public ActionResult GetDoctorList()
        {
            var data = db.doctors_info.ToList();
            return View(data);

        }

        public ActionResult InsertCustomer(customer_info cus)
        {
            customer_info customer = new customer_info()
            {
                invoice_no = cus.invoice_no,
                customer_name = cus.customer_name

            };
            db.customer_info.Add(customer);
            db.SaveChanges();
            return View();


        }

        public ActionResult InsertTable(test_tbl tbl)
        {
            test_tbl tbls = new test_tbl()
            {
                name = tbl.name,
                department = tbl.department


            };
            db.test_tbl.Add(tbls);
            db.SaveChanges();
            return View(tbls);
        }


    }



}

DMS/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DMS || @ViewBag.Title</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/assets/plugins/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/assets/plugins/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/assets/plugins/Ionicons/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/assets/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/assets/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/assets/css/skins/_all-skins.min.css">
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-green fixed sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="#" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>D</b>MS</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Admin</b>DMS</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">                    
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/assets/img/user2-160x160.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs">
                                    @if (@Session["UserId"] != null)
                                    {@Session["UserId"] }
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="~/assets/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                    <p>
                                       @Session["AdFullName"]
                                        @*Alexander Pierce - Web Developer*@
                                        <small>Member since @Session["EntryDate"]</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                @*<li class="user-body">
                                </li>*@
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                     @Html.ActionLink("Sign Out","SignIn", "Authentication")
                                        
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            @*<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>*@
                            <a href="/Authentication/Module">Module</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/assets/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                        <span class="hidden-xs">
                            @if (@Session["UserId"] != null)
                            {@Session["UserId"]}
                        </span>

                    </div>
                    <div class="pull-left info">
                        <p>Alexander Pierce</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="active">
                        <a href="/Dashboard/Index">
                            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-files-o"></i>
                            <span>Invoice</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>@Html.ActionLink("Add Invoice", "Invoice", "Diagnostic")</li>
                            <li>@Html.ActionLink("Add Expense Invoice", "Index", "Authentication")</li>                           
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-files-o"></i>
                            <span>Manage Invoice</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>@Html.ActionLink("Todays Invoice", "", "")</li>
                            <li>@Html.ActionLink("Custom Invoice", "Index", "Authentication")</li>
                            <li>@Html.ActionLink("Custom Doctor Invoice", "Index", "Authentication")</li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-users"></i>
                            <span>Doctors</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>@Html.ActionLink("Add Doctors", "doctorInfo", "Diagnostic")</li>
                            <li>@Html.ActionLink("Manage Doctors", "GetDoctorList", "Diagnostic")</li>

                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-cog"></i>
                            <span>Common Setting</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span> 
                        </a>
                        <ul class="treeview-menu">
                            <li>@Html.ActionLink("Category Setup", "Category", "Settings")</li>
                            <li>@Html.ActionLink("Sub Category", "SubCategory", "Settings")</li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-pie-chart"></i>
                            <span>General Setting</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>@Html.ActionLink("Add Admin/User", "registered", "Settings")</li>
                            <li>@Html.ActionLink("Manage Admin/User", "GetUserInfo", "Settings")</li>
                            <li>@Html.ActionLink("Company Information", "CompanyInfo", "Authentication")</li>

                        </ul>
                    </li>

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-book"></i>
                            <span>Reports</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>@Html.ActionLink("Daily Invoice Report", "", "")</li>
                            <li>@Html.ActionLink("Custom Report", "", "")</li>

                        </ul>
                    </li>          

                    <li>
                        <a href="../mailbox/mailbox.html">
                            <i class="fa fa-envelope"></i> <span>Mailbox</span>
                            <span class="pull-right-container">
                                <small class="label pull-right bg-yellow">12</small>
                                <small class="label pull-right bg-green">16</small>
                                <small class="label pull-right bg-red">5</small>
                            </span>
                        </a>
                    </li>                        
                  
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <section class="content">
                <div>
                    @RenderBody()
                </div>
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
            </div>
            <strong>Copyright &copy; @DateTime.Now.Year -</strong> 
            All rights reserved For <a href="http://www.updatetechno.net">www.updatetechno.com</a>
        </footer>

        <!-- Add the sidebar's background. This div must be placed
        immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="..//assets/plugins/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="..//assets/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- DataTables -->
    
    <!-- SlimScroll -->
    <script src="..//assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="..//assets/plugins/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="..//assets/js/adminlte.min.js"></script>
    <!-- Extra Js -->
    <script src="..//assets/js/main.js"></script>

    @RenderSection("scripts", required: false)  
    
   </body>
</html>

DMS/Views/Shared/_LayoutPartial.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title> DMS ||@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="..//assets/plugins/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="..//assets/plugins/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="..//assets/plugins/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="..//assets/css/AdminLTE.min.css">
    <link rel="stylesheet" href="..//assets/css/skins/_all-skins.min.css">
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-green layout-top-nav">
    <div class="wrapper">
        <header class="main-header fixed">
            <nav class="navbar navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <a href="#" class="navbar-brand"><b>Admin</b>DMS</a>
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                        <ul class="nav navbar-nav">
                            <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">Link</a></li>-->
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Invoice <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Todays Invoice</a></li>
                                    <li>@Html.ActionLink("Custom Invoice", "CustomInvoice", "Diagnostic")</li>
                                    <li><a href="#">Something else here</a></li>
                               
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Reports <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Todays Invoice</a></li>
                                    <li><a href="#">Custom Invoice</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <!--<li class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">One more separated link</a></li>-->
                                </ul>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-left" role="search">
                            <div class="form-group">
                                <input type="text" class="form-control" id="navbar-search-input" placeholder="Search">
                            </div>
                        </form>
                    </div>
                    <!-- /.navbar-collapse -->
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- User Account Menu -->
                            <li class="dropdown user user-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <!-- The user image in the navbar-->
                                    <img src="~/assets/img/user2-160x160.jpg" class="user-image" alt="User Image">
                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                    <span class="hidden-xs">
                                        @Session["UserId"]
                                        @*@if (@ViewBag.UserName != null)
                                        {@ViewBag.UserName }*@
                                    </span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- The user image in the menu -->
                                    <li class="user-header">
                                        <img src="~/assets/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                        <p>
                                            @Session["OpFullName"]
                                            <small>Member since Nov. 2012</small>
                                        </p>
                                    </li>
                                    <!-- Menu Body -->
                                 
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="#" class="btn btn-default btn-flat">Profile</a>
                                        </div>
                                        <div class="pull-right">
                                            <!--<a href="#" class="btn btn-default btn-flat">Sign out</a> -->
                                            @Html.ActionLink("SignIn", "SignIn", "Authentication")
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <!-- /.navbar-custom-menu -->
                </div>
                <!-- /.container-fluid -->
            </nav>
        </header>
        <!-- Full Width Column -->
        <div class="content-wrapper fixed">
            @*<div class="container">*@
                <!-- Main content -->
                <section class="content">
                    <div>
                        @RenderBody()
                    </div>
                </section>
                <!-- /.content -->
            @*</div>*@
            <!-- /.container -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="container">
                <div class="pull-right hidden-xs">
                </div>
                <strong>Copyright &copy; @DateTime.Now.Year -</strong>
                All rights reserved For <a href="http://www.updatetechno.net">www.updatetechno.com</a>
            </div>
            <!-- /.container -->
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/assets/plugins/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/assets/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="~/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/assets/plugins/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/assets/js/adminlte.min.js"></script>
    <!-- Extra Js -->
    <script src="~/assets/js/main.js"></script>
</body>
</html>