DMS/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using DMS.Models;
using System.IO;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;

namespace DMS.Controllers
{
    public class ReportController : Controller
    {
        //
        // GET: /Report/
        DiagnosticMS_DBContext db = new DiagnosticMS_DBContext();
        public ActionResult Lists()
        {
            var testList = db.test_tbl.ToList();
            return View(testList);
        }
        public ActionResult ShowTestReports()
        {

            var testList = db.test_tbl.ToList();
            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Reports"), "testReport.rpt"));

            rd.SetDataSource(testList);

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();


            Stream stream = rd.ExportToStream(ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);
            return File(stream, "application/pdf", "CustomerList.pdf");



        }
        //public FileResult GetReport()
        //{
        //    string ReportURL = "{Your File Path}";
        //    byte[] FileBytes = System.IO.File.ReadAllBytes(ReportURL);
        //    return File(FileBytes, "application/pdf");  


        //}

	}
}

DMS/Views/Report/Lists.cshtml
@model IEnumerable<DMS.Models.test_tbl>

@{
    ViewBag.Title = "Lists";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    
}

<h2>Lists</h2>

<p>
    @Html.ActionLink("Create New", "Create")||
    @Html.ActionLink("Download Report", "ShowTestReports", "Report", new { target = "_blank" })

</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.department)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.department)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

DMS/Views/Report/ShowTestReport.cshtml
@{
    ViewBag.Title = "ShowTestReport";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<div>
    @*<a href="@Url.Action("ShowTestReport", new { target = "_blank" })">Report</a>*@
@Html.ActionLink("New report", "ShowTestReports", "Report", null, new { target = "_blank" });

    <script>

    </script>

</div>
<h2>ShowTestReport</h2>

DMS/Views/Report/printView.cshtml
@{
    ViewBag.Title = "printView";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>printView</h2>